### ISSUE TITLE
pro bono

### ISSUE THREAD

**Issue by blackgirlbytes** [blackgirlbytes/test-dwn#21]
## 🚀 Goal
We want to ensure our website's documentation don't have any mistakes.

## 🤔 Background
This issue focuses specifically on fixing typos across our docs. Your contributions here make a difference!

## 🤝 How You Can Contribute
We've broken it down into specific typos for you to address. Every contribution counts!

### **❗You must only assign yourself one task at a time to give everyone a chance to participate.❗**
You may assign yourself your next task after your current task is reviewed & accepted.
1. Fix Typos in Credential Issuance [page](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance)
    - [ ] Fix "implmented" to "implemented"
![image](https://github.com/user-attachments/assets/98e049e0-4bbb-404a-b866-9dcd7458bc09)
2. Make sure all tests are passing.

## 🌟 Resources
- [Credential Issuance Page](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance)
- [Docs, Developer Website](https://developer.tbd.website/docs/)

## Getting Started
1. Comment ".take" on this issue to get assigned
2. Fork the repository and create a new branch for this task
3. Follow the tasks outlined above
4. Submit a pull request with your changes
5. Respond to any feedback during the review process

## Questions?
If you have any questions or need clarification, please comment on this issue or join our [Discord](https://discord.gg/tbd) community.

Happy coding! 🎉

**Comment by ghost** [comment]
.take

**Comment by ghost** [comment]
Not getting how to do like after cloning i am trying to run but its not working and where to change after detecting typo errors

**Comment by ANIRUDH-333** [comment]
> Not getting how to do like after cloning i am trying to run but its not working and where to change after detecting typo errors

- Create a new branch in the forked repository
- Make your changes (fix the typos)
- Push the changes to your branch
- Now, you will see and option "Compare & Create a Pull Request"
- Create the PR

**Comment by blackgirlbytes** [comment]
oh @ANIRUDH-333 and @krishnkant-singh these are not real issues for Hacktoberfest. I'm so sorry! I was actually just making these issues to test a github action for the real Hactkoberfest projects that I have running. Take a look at these instead:
- https://github.com/TBD54566975/developer.tbd.website/issues/1552
- https://github.com/TBD54566975/tbd-examples/issues/63
- https://github.com/TBD54566975/tbd-examples/issues/81
- https://github.com/TBD54566975/dwn-sdk-js/issues/806
